{{- if not .Values.credentialStorage.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "collectorctrl-operator.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if ne .Values.credentialStorage.storageClassName nil }}
  storageClassName: {{ .Values.credentialStorage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.credentialStorage.size }}
{{- end }}
